micronaut:
  application:
    name: myplanes
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - ${FRONTEND_URL:http://localhost:8080}
          allowedMethods:
            - GET
            - PATCH
            - DELETE
            - POST
            - PUT
  ssl:
    enabled: ${SSL_ENABLED:false}
    keyStore:
      path: "file:${SSL_CERT_PATH}"
      password: "${SSL_CERT_PASSWORD}"
      type: "${KEYSTORE_TYPE}"

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

openskyapi:
  url: "https://opensky-network.org"
  user: ${OPENSKY_API_USER}
  password: ${OPENSKY_API_PASSWORD}

google:
  config:
    path: ${GOOGLE_CONFIG_PATH}
    databaseUrl: ${GOOGLE_CONFIG_DATABASE_URL}

aircraft-data-file:
  path: ${AIRCRAFT_DATA_FILE}