micronaut:
  application:
    name: myplanes
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - ${FRONTEND_URL}
          allowedMethods:
            - GET
            - PATCH
            - DELETE
            - POST
            - PUT
  ssl:
    enabled: ${SSL_ENABLED:true}
    keyStore:
      path: "file:${SSL_CERT_PATH}"
      password: "${SSL_CERT_PASSWORD}"
      type: "${KEYSTORE_TYPE}"

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

openskyapi:
  user: ${OPENSKY_API_USER}
  password: ${OPENSKY_API_PASSWORD}

google:
  config:
    path: ${GOOGLE_CONFIG_PATH}
    databaseUrl: ${GOOGLE_CONFIG_DATABASE_URL}

storage.redis:
  expireAfterSeconds: ${STORAGE_REDIS_EXPIRE_AFTER_SECONDS}

job-config-file:
  path: ${JOB_CONFIG_FILE_PATH}

aircraft-data-file:
  path: ${AIRCRAFT_DATA_FILE}