# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set version = build number
        run: mvn versions:set -DnewVersion=$GITHUB_RUN_NUMBER -DprocessAllModules=true
      - name: Build with Maven
        run: mvn clean package
      - name: Set commit id variable
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: create 'app_versions' directory if it does not exist
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_MYPLANES_USER }}
          key: ${{ secrets.DO_MYPLANES_KEY }}
          port: 22
          script_stop: true
          script: |
            mkdir -p /home/myplanes/app_versions
      - name: upload package to DO
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_MYPLANES_USER }}
          key: ${{ secrets.DO_MYPLANES_KEY }}
          port: 22
          strip_components: 2
          source: "app/target/app-$GITHUB_RUN_NUMBER.jar"
          target: "/home/myplanes/app_versions"
